export const PROJECTS = [
  {
    id: 1,
    titleKey: "projects.tiemMriem.title",
    descKey: "projects.tiemMriem.desc",
    image: "/projects/TIEM MRIEM/images/Untitled--TIEM-MARIM-MOCKUP.png",
    images: ["/projects/TIEM MRIEM/images/Untitled--TIEM-MARIM-MOCKUP.png"],
    category: "social",
    tagKey: "projects.tiemMriem.tag",
    resultKey: "projects.tiemMriem.result",
    year: "2024",
    size: "large",
    gradient: "linear-gradient(135deg, #2d0a1a 0%, #4a1030 50%, #2d0a1a 100%)",
    client: "Team Meriem — Farmasi Maroc",
    services: ["Social Media Design", "Brand Identity", "Content Creation"],
  },
  {
    id: 2,
    titleKey: "projects.sofra.title",
    descKey: "projects.sofra.desc",
    image: "/projects/sofra/sofra/Untitled-1.png",
    images: ["/projects/sofra/sofra/Untitled-1.png"],
    category: "branding",
    tagKey: "projects.sofra.tag",
    resultKey: "projects.sofra.result",
    year: "2025",
    size: "medium",
    gradient: "linear-gradient(135deg, #1a0f00 0%, #3d2400 100%)",
    client: "Sofra — Saveur de l'Hospitalité",
    services: ["Social Media Posts", "Food Photography Design", "Brand Strategy"],
  },
  {
    id: 3,
    titleKey: "projects.mohammedElBouhli.title",
    descKey: "projects.mohammedElBouhli.desc",
    image: "/projects/MOHAMMED-EL-BOUHLI/carosil-MOHAMMED-EL-BOUHLI_01.png",
    images: ["/projects/MOHAMMED-EL-BOUHLI/carosil-MOHAMMED-EL-BOUHLI_01.png"],
    category: "branding",
    tagKey: "projects.mohammedElBouhli.tag",
    resultKey: "projects.mohammedElBouhli.result",
    year: "2024",
    size: "medium",
    gradient: "linear-gradient(135deg, #002a2a 0%, #004d4d 100%)",
    client: "Mohammed El Bouhli — Pro Therapy",
    services: ["Full Brand Identity", "Social Media", "Video Editing", "Content Strategy"],
  },
  {
    id: 4,
    titleKey: "projects.livrone.title",
    descKey: "projects.livrone.desc",
    image: "/projects/livrone/LivrOne-Recovered.png",
    images: ["/projects/livrone/LivrOne-Recovered.png"],
    category: "social",
    tagKey: "projects.livrone.tag",
    resultKey: "projects.livrone.result",
    year: "2025",
    size: "large",
    gradient: "linear-gradient(135deg, #2d1a00 0%, #4d2e00 50%, #2d1a00 100%)",
    client: "LivrOne — Food Delivery App",
    services: ["Social Media Design", "App Promo Content", "Ad Creatives"],
  },
  {
    id: 5,
    titleKey: "projects.roaa.title",
    descKey: "projects.roaa.desc",
    image: "/projects/La Maison Roaa - Site Web de Réservation Restaurant/home-hero.jpg",
    images: [
      "/projects/La Maison Roaa - Site Web de Réservation Restaurant/home-hero.jpg",
      "/projects/La Maison Roaa - Site Web de Réservation Restaurant/menu-page.jpg",
      "/projects/La Maison Roaa - Site Web de Réservation Restaurant/our-story.jpg",
      "/projects/La Maison Roaa - Site Web de Réservation Restaurant/reservation-confirmation.jpg",
      "/projects/La Maison Roaa - Site Web de Réservation Restaurant/reservation-form.jpg",
      "/projects/La Maison Roaa - Site Web de Réservation Restaurant/testimonials.jpg",
    ],
    category: "webApp",
    tagKey: "projects.roaa.tag",
    resultKey: "projects.roaa.result",
    year: "2024",
    size: "large",
    gradient: "linear-gradient(135deg, #1f1f1f 0%, #3a3a3a 100%)",
    client: "La Maison Roaa",
    services: ["Web Design", "Frontend Development", "UX/UI"],
  },
  {
    id: 6,
    titleKey: "projects.mci.title",
    descKey: "projects.mci.desc",
    image: "/projects/Mci Luxury/Screenshot 2026-03-26 134425.png",
    images: [
      "/projects/Mci Luxury/Screenshot 2026-03-26 134337.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134425.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134453.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134509.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134533.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134604.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134710.png",
      "/projects/Mci Luxury/Screenshot 2026-03-26 134744.png",
    ],
    category: "webApp",
    tagKey: "projects.mci.tag",
    resultKey: "projects.mci.result",
    year: "2024",
    size: "medium",
    gradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    client: "Mci Luxury",
    services: ["Web Development", "Luxury Car Rental Booking"],
  },
  {
    id: 7,
    titleKey: "projects.palmerie.title",
    descKey: "projects.palmerie.desc",
    image: "/projects/Palmerie Quad/home-hero.jpg",
    images: [
      "/projects/Palmerie Quad/home-hero.jpg",
      "/projects/Palmerie Quad/activities.jpg",
      "/projects/Palmerie Quad/im.jpg",
      "/projects/Palmerie Quad/image.jpg",
      "/projects/Palmerie Quad/image1.jpg",
      "/projects/Palmerie Quad/reivews.jpg",
    ],
    category: "webApp",
    tagKey: "projects.palmerie.tag",
    resultKey: "projects.palmerie.result",
    year: "2024",
    size: "medium",
    gradient: "linear-gradient(135deg, #422006 0%, #78350f 100%)",
    client: "Palmerie Quad",
    services: ["Web Design", "Tourism Booking System"],
  },
  {
    id: 8,
    titleKey: "projects.itranweb.title",
    descKey: "projects.itranweb.desc",
    image: "/projects/itranweb/photo_2026-03-26_15-36-04.jpg",
    images: [
      "/projects/itranweb/photo_2026-03-26_15-36-04.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-27.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-30.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-33.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-36.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-40.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-43.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-47.jpg",
      "/projects/itranweb/photo_2026-03-26_15-36-50.jpg",
    ],
    category: "marketingAds",
    tagKey: "projects.itranweb.tag",
    resultKey: "projects.itranweb.result",
    year: "2023",
    size: "large",
    gradient: "linear-gradient(135deg, #172554 0%, #1e40af 100%)",
    client: "Itranweb",
    services: ["Marketing & Ads", "Campaign Strategy", "Social Media"],
  }
];

export const CATEGORIES = [
  { key: "all",          labelKey: "categories.all"          },
  { key: "social",       labelKey: "categories.social"       },
  { key: "branding",     labelKey: "categories.branding"     },
  { key: "webApp",       labelKey: "categories.webApp"       },
  { key: "marketingAds", labelKey: "categories.marketingAds" },
];

export const MARQUEE_ITEMS = [
  "Website Design","Social Media","Brand Strategy",
  "Photo & Video","Content Creation","Paid Ads","App Development","SEO Growth",
];
